<#import "decorator.ftl" as decorator />

<@decorator.layout>
Yoruba name dictionary app.

<#--Commenting these out for now <h4>Dashboard</h4>-->
<#--Go to <a href="/dashboardapp/index.html#/home">dashboard</a>-->

<#--<h4>Template</h4>-->
<#--View <a href="/template">template</a>-->

<hr/>

<h4>Text To Speech Stub (WIP)</h4>

<div id="tts-left">
Enter name <br/>
<input id="nametts" type="text"/>
<input id="submittts" type="button" value="Get Pronunciation" style="margin-top:-10px">
<br/>
<div id="ttsPlayer">

</div>
</div>

<div id="tts-right">

    More information on tone segment here: <a href="https://drive.google.com/open?id=0B0KSTIwO48rtR1ZMVWlBcHNJQWs&authuser=0" target="_blank"> Permutation file on Google doc </a>

    <br/><strong>Available Segments</strong> <br/>
    <div id="segments">
        gbi_l.wav
        go_m.wav
        ho_r.wav
        re_f.wav
        gbo_m.wav
        fee_r.wav
        se_m.wav
        koo_m.wav
        gbu_l.wav
        ra_m.wav
        me_h.wav
        yee_r.wav
        koo_r.wav
        nee_m.wav
        la_m.wav
        mi_l.wav
        du_m.wav
        ga_l.wav
        soo_m.wav
        yu_m.wav
        she_l.wav
        ne_l.wav
        foo_r.wav
        bee_l.wav
        lee_m.wav
        ta_h.wav
        fa_r.wav
        gi_h.wav
        kpe_r.wav
        he_m.wav
        ki_r.wav
        je_m.wav
        wa_m.wav
        gbee_r.wav
        see_r.wav
        ji_r.wav
        foo_h.wav
        kpoo_m.wav
        ba_l.wav
        kpo_r.wav
        di_l.wav
        fu_m.wav
        tu_l.wav
        shoo_l.wav
        be_m.wav
        la_h.wav
        doo_r.wav
        joo_m.wav
        ka_l.wav
        bi_h.wav
        loo_m.wav
        kpee_h.wav
        hu_l.wav
        roo_r.wav
        ti_r.wav
        ki_m.wav
        tu_r.wav
        gu_l.wav
        goo_r.wav
        sa_m.wav
        si_l.wav
        je_r.wav
        ne_m.wav
        shu_h.wav
        ba_m.wav
        ni_h.wav
        ho_h.wav
        joo_h.wav
        ne_r.wav
        gba_m.wav
        le_l.wav
        su_m.wav
        wo_r.wav
        gee_h.wav
        hoo_r.wav
        lee_h.wav
        re_r.wav
        sha_h.wav
        hee_l.wav
        ke_f.wav
        noo_l.wav
        wa_l.wav
        ma_m.wav
        mee_h.wav
        ru_h.wav
        hi_l.wav
        ke_h.wav
        dee_h.wav
        ri_r.wav
        yo_h.wav
        lo_l.wav
        ho_l.wav
        fa_h.wav
        da_l.wav
        do_h.wav
        mo_l.wav
        gi_r.wav
        wi_r.wav
        be_l.wav
        see_l.wav
        lee_l.wav
        sa_h.wav
        go_l.wav
        ma_l.wav
        wo_l.wav
        gu_m.wav
        si_h.wav
        too_l.wav
        de_h.wav
        no_r.wav
        fa_l.wav
        nu_l.wav
        ya_r.wav
        na_r.wav
        bi_m.wav
        me_f.wav
        bu_h.wav
        doo_m.wav
        shoo_h.wav
        yee_h.wav
        bee_m.wav
        boo_r.wav
        hu_h.wav
        kpoo_h.wav
        ke_m.wav
        gbi_m.wav
        gbu_h.wav
        roo_h.wav
        to_r.wav
        shoo_m.wav
        hoo_m.wav
        te_h.wav
        de_l.wav
        kpi_r.wav
        wee_r.wav
        gbe_h.wav
        she_m.wav
        fi_m.wav
        we_r.wav
        su_l.wav
        joo_l.wav
        dee_l.wav
        gee_m.wav
        la_r.wav
        hee_h.wav
        wa_h.wav
        ye_h.wav
        tee_m.wav
        shee_r.wav
        ma_h.wav
        soo_h.wav
        she_h.wav
        hi_m.wav
        yi_m.wav
        ta_l.wav
        go_r.wav
        ka_r.wav
        mee_m.wav
        do_m.wav
        we_m.wav
        gbee_h.wav
        gbee_l.wav
        la_l.wav
        no_l.wav
        me_l.wav
        gee_r.wav
        ku_m.wav
        kpi_h.wav
        fe_h.wav
        bi_r.wav
        ji_h.wav
        moo_h.wav
        mu_m.wav
        joo_r.wav
        na_m.wav
        me_r.wav
        ka_m.wav
        mee_r.wav
        ki_l.wav
        fu_h.wav
        soo_f.wav
        roo_m.wav
        ye_m.wav
        gbi_h.wav
        du_h.wav
        kpa_h.wav
        ye_l.wav
        bu_m.wav
        loo_l.wav
        hi_r.wav
        see_m.wav
        bo_l.wav
        shee_m.wav
        moo_l.wav
        ra_r.wav
        ni_r.wav
        we_l.wav
        kee_m.wav
        ba_h.wav
        gboo_h.wav
        fi_h.wav
        see_h.wav
        yi_r.wav
        te_m.wav
        wu_h.wav
        gboo_r.wav
        jo_r.wav
        me_m.wav
        wee_m.wav
        sha_m.wav
        shee_l.wav
        ga_h.wav
        di_r.wav
        bo_h.wav
        lo_m.wav
        moo_r.wav
        ju_r.wav
        ja_l.wav
        ri_h.wav
        yo_l.wav
        kpee_l.wav
        ku_h.wav
        ro_l.wav
        kpu_f.wav
        mo_m.wav
        na_h.wav
        gba_h.wav
        ta_r.wav
        to_m.wav
        ri_l.wav
        doo_h.wav
        no_m.wav
        mo_h.wav
        yi_h.wav
        ko_h.wav
        li_l.wav
        goo_m.wav
        sho_r.wav
        lee_r.wav
        shu_l.wav
        wi_h.wav
        hu_r.wav
        ha_r.wav
        he_r.wav
        too_m.wav
        kpa_r.wav
        ge_h.wav
        wu_l.wav
        gba_r.wav
        wo_h.wav
        kpo_l.wav
        so_r.wav
        kpe_h.wav
        ra_h.wav
        be_r.wav
        roo_l.wav
        kpe_l.wav
        moo_m.wav
        koo_l.wav
        nu_m.wav
        fo_l.wav
        yoo_l.wav
        gbe_m.wav
        be_h.wav
        shi_r.wav
        sa_f.wav
        bo_m.wav
        kpu_l.wav
        lo_h.wav
        wu_r.wav
        fee_h.wav
        do_l.wav
        le_h.wav
        gbe_l.wav
        mi_m.wav
        he_l.wav
        ku_l.wav
        ja_h.wav
        fo_h.wav
        kpi_m.wav
        yo_r.wav
        kpo_m.wav
        ro_h.wav
        se_h.wav
        kpo_h.wav
        ja_m.wav
        ji_l.wav
        je_h.wav
        li_h.wav
        ko_m.wav
        kpu_h.wav
        bu_r.wav
        ri_m.wav
        de_m.wav
        ru_f.wav
        kpa_l.wav
        su_r.wav
        ma_r.wav
        fi_r.wav
        mee_l.wav
        ge_m.wav
        gbu_m.wav
        shi_m.wav
        gboo_l.wav
        te_r.wav
        wo_m.wav
        gbo_l.wav
        yoo_h.wav
        mi_r.wav
        jee_m.wav
        gbo_r.wav
        bi_l.wav
        hu_m.wav
        kee_r.wav
        yu_h.wav
        bu_l.wav
        shee_h.wav
        fo_r.wav
        sho_l.wav
        loo_h.wav
        ju_l.wav
        woo_h.wav
        kpu_r.wav
        ti_l.wav
        noo_m.wav
        re_h.wav
        ge_l.wav
        tee_h.wav
        gbo_h.wav
        ha_h.wav
        se_r.wav
        gee_l.wav
        nu_r.wav
        ka_h.wav
        yi_l.wav
        kee_l.wav
        yoo_m.wav
        kpu_m.wav
        kpoo_r.wav
        hoo_h.wav
        gboo_m.wav
        ro_m.wav
        gba_l.wav
        bee_h.wav
        wee_h.wav
        wu_m.wav
        jee_l.wav
        ko_r.wav
        dee_r.wav
        mu_h.wav
        kpa_m.wav
        ja_r.wav
        da_r.wav
        te_l.wav
        we_h.wav
        da_m.wav
        boo_l.wav
        gbe_r.wav
        doo_l.wav
        ga_m.wav
        noo_r.wav
        hi_h.wav
        na_l.wav
        ha_l.wav
        to_h.wav
        fu_l.wav
        sho_m.wav
        mu_l.wav
        si_m.wav
        gu_h.wav
        goo_l.wav
        se_l.wav
        gu_r.wav
        fee_m.wav
        jee_h.wav
        kpi_f.wav
        too_r.wav
        ru_l.wav
        goo_h.wav
        she_r.wav
        ko_l.wav
        yu_r.wav
        ya_h.wav
        kpe_m.wav
        gi_l.wav
        so_h.wav
        lo_r.wav
        woo_m.wav
        ha_f.wav
        he_h.wav
        go_h.wav
        nee_h.wav
        ta_m.wav
        to_l.wav
        lu_m.wav
        de_r.wav
        sa_r.wav
        tee_r.wav
        ru_m.wav
        re_m.wav
        shu_m.wav
        he_f.wav
        too_h.wav
        je_l.wav
        no_h.wav
        yo_m.wav
        ba_r.wav
        nee_l.wav
        ge_r.wav
        woo_r.wav
        lu_h.wav
        ru_r.wav
        gbu_r.wav
        ju_m.wav
        tee_l.wav
        hee_m.wav
        yu_l.wav
        ku_r.wav
        le_m.wav
        mi_h.wav
        foo_m.wav
        ni_m.wav
        shoo_r.wav
        ra_l.wav
        wi_m.wav
        dee_m.wav
        jee_r.wav
        da_h.wav
        sha_r.wav
        tu_m.wav
        yee_m.wav
        boo_h.wav
        li_r.wav
        ni_l.wav
        du_l.wav
        su_h.wav
        soo_r.wav
        yee_l.wav
        kpee_m.wav
        jo_l.wav
        hee_r.wav
        ya_m.wav
        gbi_r.wav
        kee_h.wav
        ti_h.wav
        loo_r.wav
        sho_h.wav
        fu_r.wav
        tu_h.wav
        jo_h.wav
        ha_m.wav
        mo_r.wav
        hoo_l.wav
        ho_m.wav
        ke_l.wav
        fe_r.wav
        nu_h.wav
        ji_m.wav
        kpee_r.wav
        bo_r.wav
        ro_r.wav
        ki_h.wav
        fi_l.wav
        du_r.wav
        ga_r.wav
        fe_m.wav
        boo_m.wav
        di_h.wav
        fa_m.wav
        lu_l.wav
        kpoo_f.wav
        so_l.wav
        shi_l.wav
        ti_m.wav
        di_m.wav
        woo_l.wav
        ne_h.wav
        lu_r.wav
        wi_l.wav
        wa_r.wav
        mu_r.wav
        do_r.wav
        yoo_r.wav
        ye_r.wav
        fe_l.wav
        nee_r.wav
        jo_m.wav
        fo_m.wav
        fee_l.wav
        ya_l.wav
        sha_l.wav
        bee_r.wav
        ju_h.wav
        ke_r.wav
        noo_h.wav
        le_r.wav
        si_r.wav
        li_m.wav
        wee_l.wav
        shu_r.wav
        gi_m.wav
        koo_h.wav
        gbee_m.wav
        shi_h.wav
        so_m.wav
    </div>
</div>

</@decorator.layout>
